{% set name = "pyfab" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfab-{{ version }}.tar.gz
  sha256: fff612517cc3f24c23c0314bc115d7ba092c26b9a4823984b01d081926070960

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fslpy
    - nibabel
    - numpy
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - fabber
    - fabber.test

about:
  home: https://fabber_core.readthedocs.io/
  summary: Python interface to the Fabber toolkit for Bayesian model fitting
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
